name: Angular Portfolio CI/CD pipeline learning

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch: # Manual trigger
  push: # Runs on pushes to main or dev
    branches: [ main, dev ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Supports lockfileVersion@2
      - name: Install Dependencies
        run: npm ci # Downloads reactive-lint
      - name: Verify reactive-lint Installation
        run: npm list reactive-lint || true # Logs version, continues if fails
      - name: Run Linting with reactive-lint
        run: npm run lint || true # Continues if linting fails
      - name: Run Unit Tests
        run: npm run test -- --watch=false || true # Continues if tests fail
      - name: Build Angular Project
        run: npm run build -- --prod # Production build
